appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
travis:
  secure:
    BINSTAR_TOKEN: G8TYhOizskIIs7oXHdB7SLFXpADu0AfBjmVanJs1cYJ0JhPbnabAyFR1RvSKRKss8Tocl1boXXaqcTU2Z0IE0YG5a5dXUx/KQAExUVP5kUKTyOuOXi5RDaaGJi/+VQst5m4bUWB6+tkiQ+cMgV+/0ExCb4Hzdueq4j2prIa/w2VgUNOgnOr6WqHsSxGx2KGj4upc8ogYtIbWzG9cmCUB6tiWJVSejkrR7c/KRpK7ZTjvZcZzx30Pc2DXwmDEFbMXAHyx29Bn66NwRegCE0d13FhFPFCXnaM8IeV+5r3Mkdk2qZNcqnCHXszSasnOceGaJZNj+X0ia1Ku7EBqBa8Tp0vDWv6H/2YScS/0/7nKMLwNsjsMDavAyc5LPUZMwHkBfYol/NQvUVPtzCZbpFKSod5KXwJqRUJ9kVp3glSRhaGM1zQUm+/WOlkOA7OQbjJWfjpbU9dJuASjS+dQIh9dj7YAbZTbcnE3jurwVKKmoxPeFibgUIfqHaoRk+9DBPfE/bj4IPk4iQJkQFWyWgl/ikHlwFFTYacgfDAJ7HfSuJQdWSCf51gISsQqZrW6wuly1sJ3JDENUDJpvTmgljFOR8bZiKrOeYER5kP6L7QU9MIJ1SIEWWvgpljEo7fz2Vo692ZbFYnHkazMCOe6NHF9qgB8IaxgKkyEgQp2zAHQlX0=
